/**
 * The **authoring** category: the shipped `lint` engine adapted into the
 * `check` envelope — same content dirs, same `.nimbus/lint.json` severities,
 * same rules, each `Diagnostic` mapped through `fromDiagnostic`. Unlike `lint`,
 * a zero-`.mdx` project is NOT an error: a config-only `check` must still pass.
 */

import fs from "node:fs";
import path from "node:path";

import {
  findMdxFiles,
  lintPaths,
  validateLintOptions,
  IMPLEMENTED_CODES,
  type CollectionsConfig,
  type RulesConfig,
} from "../lint/index.js";
import { fromDiagnostic, type CheckFinding } from "./finding.js";

export function checkAuthoring(cwd: string): CheckFinding[] {
  const findings: CheckFinding[] = [];
  const { config, error } = loadMaterializedConfig(cwd);

  // A present-but-broken `.nimbus/lint.json` is a real error, not a silent "run
  // zero rules": defaulting to `{}` would make every opt-in rule resolve `off`
  // and print a false-green `Authoring ✓ ok`. Surface it; the run exits 1.
  if (error) {
    findings.push({
      scope: "authoring",
      code: "nimbus/lint-config-invalid",
      severity: "error",
      file: ".nimbus/lint.json",
      message: `${error} Delete the file (it's regenerated by \`astro build\`) or fix it.`,
      fixable: false,
    });
  }

  const files = findMdxFiles([path.join(cwd, "src", "content")]);
  if (files.length === 0) return findings; // config-only project — not a failure

  const diagnostics = lintPaths(files, cwd, config);
  return [...findings, ...diagnostics.map(fromDiagnostic)];
}

export interface MaterializedConfig {
  rules: RulesConfig;
  collections: CollectionsConfig;
  site?: string;
}

export interface LoadMaterializedResult {
  config: MaterializedConfig;
  /** Non-null when the file exists but couldn't be parsed/validated. */
  error: string | null;
}

/**
 * Read the materialized lint config from `.nimbus/lint.json`, distinguishing
 * three cases so callers never confuse "no config yet" with "broken config":
 * absent → defaults + `error: null`; present-but-invalid → defaults + `error`
 * set; valid → the materialized severities. Returns the error (rather than
 * process-exiting like `lint`) so the envelope can carry it as a finding.
 */
export function loadMaterializedConfig(cwd: string): LoadMaterializedResult {
  const file = path.join(cwd, ".nimbus", "lint.json");
  const rel = ".nimbus/lint.json";
  let raw: string;
  try {
    raw = fs.readFileSync(file, "utf8");
  } catch {
    return { config: { rules: {}, collections: {} }, error: null };
  }

  let parsed: { rules?: unknown; collections?: unknown; site?: unknown };
  try {
    parsed = JSON.parse(raw) as typeof parsed;
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err);
    return {
      config: { rules: {}, collections: {} },
      error: `${rel} is not valid JSON — ${detail}.`,
    };
  }

  try {
    const validated = validateLintOptions(
      { rules: parsed.rules, collections: parsed.collections },
      IMPLEMENTED_CODES,
    );
    const site = typeof parsed.site === "string" ? parsed.site : undefined;
    return {
      config: { rules: validated.rules, collections: validated.collections, site },
      error: null,
    };
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err);
    return { config: { rules: {}, collections: {} }, error: `${rel} is invalid — ${detail}.` };
  }
}
